name: Build and Test
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    
    - name: Substitute variables
      uses: microsoft/variable-substitution@v1 
      with:
        files: 'src/Genesis.Case/Api/appsettings.json'
      env:
        Email.Login: ${{ secrets.EMAIL_ADDRESS }}
        Email.Password: ${{ secrets.EMAIL_PASSWORD }}
    
    - name: Restore dependencies
      run: dotnet restore ./src/Genesis.Case
    
    - name: Build
      run: dotnet build ./src/Genesis.Case --no-restore
    
    - name: Test
      run: dotnet test ./src/Genesis.Case --no-build --verbosity normal
