name: Push Docker Image

on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Substitute variables
      uses: microsoft/variable-substitution@v1 
      with:
        files: 'src/Genesis.Case/Api/appsettings.json'
      env:
        Email.Login: ${{ secrets.EMAIL_ADDRESS }}
        Email.Password: ${{ secrets.EMAIL_PASSWORD }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: Generate build number
      uses: einaregilsson/build-number@v3
      with:
        token: ${{secrets.github_token}}

    - name: Build Docker Image
      run: |
        docker build . --tag ghcr.io/bardin08/genesis-case-task-${{steps.extract_branch.outputs.branch}}:${{BUILD_NUMBER}}
        docker push ghcr.io/bardin08/genesis-case-task-${{steps.extract_branch.outputs.branch}}:${{BUILD_NUMBER}}
